# Generated by Django 4.2 on 2023-04-07 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_name', models.CharField(max_length=255, unique=True, verbose_name='Tên bot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system_message', models.TextField()),
                ('is_public', models.BooleanField(default=False, help_text='False: Privatebot, True: Publicbot')),
                ('languageCode', models.CharField(max_length=10, verbose_name='Ngôn ngữ')),
                ('isMessage', models.TextField()),
                ('userMessage_backgroundColor', models.CharField(max_length=20)),
                ('userMessage_color', models.CharField(max_length=20)),
                ('botMessage_backgroundColor', models.CharField(max_length=20)),
                ('botMessage_color', models.CharField(max_length=20)),
                ('boxChat_backgroundColor', models.CharField(max_length=20)),
                ('boxChat_title', models.CharField(blank=True, max_length=255)),
                ('boxChat_subTitle', models.CharField(blank=True, max_length=255)),
                ('boxChat_colorWidgetBg', models.CharField(blank=True, max_length=20)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo bot')),
            ],
        ),
    ]
