# Generated by Django 4.2 on 2023-04-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_alter_botmodel_botmessage_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmodel',
            name='botMessage_backgroundColor',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='botMessage_color',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='boxChat_backgroundColor',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='boxChat_colorWidgetBg',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='boxChat_subTitle',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='boxChat_title',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='userMessage_backgroundColor',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='userMessage_color',
        ),
        migrations.CreateModel(
            name='BotModelStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMessage_backgroundColor', models.CharField(default='#1a94da', max_length=20)),
                ('userMessage_color', models.CharField(default='#fff', max_length=20)),
                ('botMessage_backgroundColor', models.CharField(default='#edf2f7', max_length=20)),
                ('botMessage_color', models.CharField(default='#000000', max_length=20)),
                ('boxChat_backgroundColor', models.CharField(default='#000000', max_length=20)),
                ('boxChat_title', models.CharField(blank=True, max_length=255)),
                ('boxChat_subTitle', models.CharField(blank=True, max_length=255)),
                ('boxChat_colorWidgetBg', models.CharField(blank=True, max_length=20)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_styles', to='bot_api.botmodel')),
            ],
        ),
    ]
