# Generated by Django 4.1.7 on 2023-04-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0003_remove_botmodel_botmessage_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotModelSetting',
            fields=[
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='bot_api.botmodel')),
                ('is_public', models.BooleanField(default=False, help_text='False: Privatebot, True: Publicbot')),
                ('languageCode', models.CharField(max_length=10, verbose_name='Ngôn ngữ')),
                ('isMessage', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotStyle',
            fields=[
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='styles', serialize=False, to='bot_api.botmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='isMessage',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='botmodel',
            name='languageCode',
        ),
        migrations.CreateModel(
            name='BotMessageStyle',
            fields=[
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='botMessage', serialize=False, to='bot_api.botstyle')),
                ('backgroundColor', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='boxChatStyle',
            fields=[
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='boxChat', serialize=False, to='bot_api.botstyle')),
                ('backgroundColor', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('subTitle', models.TextField(blank=True)),
                ('colorWidgetBg', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageStyle',
            fields=[
                ('style', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userMessage', serialize=False, to='bot_api.botstyle')),
                ('backgroundColor', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='BotModelStyles',
        ),
    ]
