# Generated by Django 4.1.7 on 2023-04-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_botmodelsetting_botstyle_remove_botmodel_ismessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDatatrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatrain', models.TextField(blank=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datatrains', to='bot_api.botmodel')),
            ],
        ),
    ]
